[package]
name = "api"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "api"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-http = "3.3"
env_logger = "0.10"
log = "0.4"
